# Generated by Django 5.1.1 on 2024-10-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('politica', 'Política'), ('deportes', 'Deportes'), ('internacionales', 'Internacionales'), ('ciencia', 'Ciencia')], default='politica', max_length=20),
        ),
    ]
