# Generated by Django 5.1.1 on 2024-10-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pics'),
        ),
    ]
